moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - real_arm
    - real_gripper

  real_arm:
    type: FollowJointTrajectory
    action_ns: /arm_controller/follow_joint_trajectory
    default: true
    joints: [joint1, joint2, joint3, joint4, joint5, joint6]

  real_gripper:
    type: FollowJointTrajectory
    action_ns: /gripper_controller/follow_joint_trajectory
    default: true
    joints: [joint7]
